sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t alexandrupeter/docker-react -f Dockerfile.dev .

script:
  - docker run alexandrupeter/docker-react npm run test -- --coverage