language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrupeter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexandrupeter/docker-react npm run test